In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dat1 = pd.read_csv('Trip183.csv')
dat2 = pd.read_csv('Zon183Unsum.csv')

/Users/ryanjcarlin/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dat2.columns

Index(['Route', 'Dir', 'Trip_ID', 'InOut', 'E/L', 'STOP_ID', 'Bearing',
       'OnStreet', 'INT', 'CrossStreet', 'Jurisdiction', 'STOP_SEQ',
       'PassingTime', 'PassingMin', 'Period', 'AveOn', 'AveOff', 'AveLd',
       'Obs', 'TRANS_LINK_ID', 'StandingLoad', 'StandingMin'],
      dtype='object')

In [5]:
trip183unsum = dat2[['Route', 'Dir', 'Trip_ID', 'InOut', 'STOP_SEQ', 'Period', 'AveOn', 'AveOff', 'AveLd', 'Obs']]
#trip183unsum.head()

In [6]:
# def period_sel(df, period, direction):
#     is_period = df['Period']==period
#     is_direction = 
#     period_routes = df[is_period]
    
#     return period_routes

In [7]:
# def in_out(df, direction):
#     is_direction = df['InOut']==direction
#     in_out = df[is_direction]
    
#     return in_out

In [8]:
def route_ridership(df, period, direction, route):
    df = df.drop(df[(df.Period != period)].index)
    df = df.drop(df[(df.InOut != direction)].index)
    df = df.drop(df[(df.Route != route)].index)
    
    final_df = df.sort_values(by=['Trip_ID', 'STOP_SEQ'])
    riders = final_df.pivot(index='STOP_SEQ', columns='Trip_ID', values='AveLd')

    return final_df, riders

In [10]:
#example48_fin

In [28]:
example45_fin, rider45 = route_ridership(trip183unsum, 'AM', 'I', 45)
rider45

Trip_ID,40570198,40570200,40570202,40570213,40570215,40570217,40570219,40570221,40570223,40570236,...,40570253,40570255,40570257,40570274,40570276,40570278,40570294,40570298,40570316,40570328
STOP_SEQ,,,,,,,,,,,,,,,,,,,,,
1.0,0.5,0.8,1.1,0.2,0.7,0.6,1.2,0.1,0.7,0.5,...,1.1,0.5,0.6,1.2,0.5,0.7,0.4,0.2,0.4,0.5
2.0,0.4,1.1,1.3,0.6,1.3,0.8,2.4,0.2,1.3,0.4,...,1.6,0.6,1.0,1.0,0.7,1.6,0.9,0.8,1.2,1.1
3.0,0.4,1.3,1.5,0.5,1.8,0.9,2.9,0.7,1.5,0.5,...,1.9,0.7,1.2,1.4,1.0,2.2,1.1,0.9,1.4,1.4
4.0,0.5,1.7,1.7,0.8,2.2,1.0,4.1,0.8,2.6,0.6,...,2.1,1.0,1.3,1.9,1.1,2.6,1.6,1.4,1.7,1.8
5.0,1.0,2.6,1.9,0.5,2.3,1.9,4.6,0.9,3.2,0.8,...,2.6,1.5,1.6,2.1,1.3,3.0,1.9,2.0,2.5,2.1
6.0,1.2,3.0,2.3,0.5,2.6,2.5,5.3,0.9,4.5,0.9,...,2.9,2.1,1.9,2.7,1.6,3.2,2.4,2.7,3.0,2.5
7.0,1.2,3.5,2.7,0.5,4.8,2.5,5.3,0.9,5.0,1.2,...,3.0,3.6,2.2,3.2,1.8,3.7,3.6,3.0,3.4,2.7
8.0,1.1,5.0,4.3,1.9,6.9,5.5,5.0,1.2,7.5,2.2,...,3.6,5.0,3.4,4.8,NaN,5.2,5.5,5.1,6.8,4.7
9.0,1.3,5.3,5.2,2.1,7.3,6.5,5.8,1.3,9.3,2.9,...,4.4,5.3,3.7,6.0,NaN,5.8,6.3,5.7,7.5,5.7
10.0,1.7,6.8,6.7,2.5,9.9,9.3,9.0,2.2,10.6,4.8,...,6.4,6.7,5.2,7.3,NaN,7.0,7.8,6.9,9.4,7.4
11.0,2.0,8.5,7.5,2.8,10.4,10.4,12.4,3.1,11.9,5.6,...,7.7,7.1,5.8,8.0,NaN,9.6,9.5,7.9,10.5,11.7
12.0,2.0,9.2,8.2,2.7,11.3,11.5,13.5,3.1,13.2,5.8,...,8.6,7.5,6.7,8.6,NaN,10.3,9.8,9.0,12.2,13.1
13.0,2.6,12.4,10.8,4.2,13.1,14.0,17.7,4.8,16.6,7.0,...,11.2,9.5,8.1,10.9,NaN,14.0,12.7,11.3,15.5,17.9
14.0,3.1,13.4,13.5,4.8,14.7,15.2,21.0,5.1,19.6,8.0,...,12.5,10.7,9.6,13.1,NaN,17.9,15.4,13.6,17.9,21.1
15.0,3.6,16.2,NaN,4.3,16.7,18.0,22.2,6.1,21.5,10.4,...,15.6,13.6,11.1,14.5,NaN,19.9,17.4,16.0,20.7,24.8
16.0,4.5,18.6,NaN,4.7,18.8,19.1,19.5,6.8,24.0,11.8,...,17.2,15.1,13.0,15.6,NaN,21.7,20.0,18.6,22.2,25.1
17.0,5.3,19.1,NaN,4.7,19.3,19.6,20.5,7.0,25.2,13.0,...,18.6,15.4,13.9,16.4,NaN,22.8,21.1,20.0,23.6,26.9
18.0,5.3,19.8,NaN,4.8,19.3,19.4,21.5,7.0,24.6,13.0,...,19.2,16.0,14.4,15.9,NaN,25.7,23.1,19.4,24.4,30.7
19.0,5.5,20.2,NaN,4.9,19.9,19.9,22.0,7.2,25.0,13.7,...,19.5,16.2,14.6,16.1,NaN,26.5,24.2,19.9,24.7,31.5
20.0,6.0,21.9,NaN,5.1,21.4,21.0,24.8,7.5,27.1,15.4,...,21.3,18.3,16.0,17.7,NaN,31.3,28.0,21.7,27.0,37.6
21.0,6.1,22.0,NaN,5.2,21.6,21.0,25.1,7.5,27.4,15.4,...,21.5,18.4,16.1,17.9,NaN,31.5,28.4,21.8,27.1,37.8
22.0,6.2,22.4,NaN,5.2,22.4,21.8,25.6,7.5,28.3,15.8,...,22.0,18.8,16.3,18.3,NaN,32.5,29.3,22.5,27.7,39.1
23.0,6.4,24.6,NaN,5.1,23.6,23.1,26.1,7.8,29.0,16.7,...,22.8,19.6,17.0,19.2,NaN,33.6,29.4,23.4,28.3,40.1
24.0,6.9,27.4,NaN,5.1,26.3,23.9,27.9,8.2,32.1,16.2,...,24.3,20.5,18.8,21.0,NaN,36.4,32.6,26.6,31.7,42.8
25.0,6.9,27.7,NaN,5.2,26.4,24.4,28.4,8.2,32.1,16.2,...,24.7,20.8,19.2,21.2,NaN,36.8,32.6,26.8,32.2,43.3
26.0,7.4,28.8,NaN,5.5,27.2,26.2,29.8,9.8,33.7,17.2,...,25.6,21.8,NaN,22.0,NaN,37.7,34.0,27.7,32.8,43.9
26.5,7.4,26.4,NaN,5.4,22.9,24.1,28.0,9.5,32.9,17.0,...,24.9,20.6,NaN,20.2,NaN,36.3,25.5,26.7,30.8,40.9
27.0,8.4,29.8,NaN,6.6,30.1,26.6,28.7,10.5,35.3,18.9,...,28.4,22.8,NaN,24.5,NaN,31.0,31.8,29.2,35.6,34.7
28.0,8.6,30.3,NaN,6.7,31.3,27.2,29.7,10.6,36.4,19.6,...,29.6,23.1,NaN,25.1,NaN,32.6,33.5,30.8,37.1,35.8
29.0,10.6,32.7,NaN,7.1,34.0,29.2,31.5,11.4,38.8,21.9,...,31.8,24.7,NaN,26.9,NaN,35.0,36.1,33.6,39.5,39.5
30.0,12.7,33.7,NaN,7.8,36.7,32.2,34.8,12.5,41.9,23.7,...,NaN,27.0,NaN,29.4,NaN,38.9,39.5,37.7,43.7,44.8
33.0,13.6,33.8,NaN,8.3,36.9,32.0,36.0,13.0,41.9,23.8,...,NaN,27.7,NaN,29.4,NaN,40.5,42.0,39.2,44.5,46.3
34.0,12.7,32.2,NaN,8.3,35.4,31.6,34.9,12.4,39.8,22.6,...,NaN,25.5,NaN,28.0,NaN,39.4,41.0,38.1,42.0,44.7
35.0,10.4,27.1,NaN,7.2,29.1,27.9,28.0,9.0,31.1,19.8,...,NaN,20.0,NaN,23.4,NaN,31.5,32.4,30.1,34.6,36.9
36.0,9.9,23.2,NaN,6.6,23.5,24.7,18.6,8.4,21.3,17.8,...,NaN,16.8,NaN,17.3,NaN,20.8,19.7,20.7,NaN,26.7
37.0,8.6,13.0,NaN,5.5,14.2,17.3,8.7,6.4,11.4,11.6,...,NaN,10.1,NaN,11.0,NaN,11.3,9.0,10.2,NaN,14.8
38.0,6.4,5.2,NaN,2.6,6.1,6.0,3.1,3.6,5.0,3.7,...,NaN,4.7,NaN,4.0,NaN,5.6,3.7,5.0,NaN,7.2
39.0,0.2,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.1,NaN,0.0

In [102]:
mean45 = pd.DataFrame((rider45.mean(axis=1)), columns=['Mean'])
mean45.Mean*=80
mean45.head()

                Mean
STOP_SEQ
1.0        48.363636
2.0        79.272727
3.0        98.545455
4.0       134.909091
5.0       165.090909

In [13]:
trip183 = dat1[['SignRt', 'InOut', 'KeyTrip', 'BusType', 'Seats', 'Period', 'AnnRides']]
trip183.head()
#trip183.BusType.unique()

   SignRt InOut   KeyTrip  BusType  Seats Period  AnnRides
0    14.0     I  40983895       43     35     AM    4080.0
1     1.0     O  40983896       43     35     AM    3825.0
2     1.0     I  40983897       43     35     AM    3825.0
3    14.0     O  40983898       43     35     AM    7395.0
4    14.0     I  40983904       43     35     AM    9435.0

In [14]:
trip183.loc[trip183['KeyTrip'] == 40569541]

      SignRt InOut   KeyTrip  BusType  Seats Period  AnnRides
4230    48.0     I  40569541       80     58     AM    1275.0

In [15]:
trip183.loc[trip183['KeyTrip'] == 40569560]

      SignRt InOut   KeyTrip  BusType  Seats Period  AnnRides
4272    48.0     I  40569560       80     58     AM   16575.0

In [16]:
testing1 = dat2.loc[dat2['Trip_ID'] == 40569541]
tes1 = testing1[['STOP_ID', 'STOP_SEQ']]
tes1 = tes1.sort_values(by=['STOP_SEQ'])
tes1

        STOP_ID  STOP_SEQ
129536    10912       1.0
129600    10914       2.0
129765    10917       3.0
130729    29240       4.0
131139    29247       5.0
130629    25243       6.0
131026    29245       7.0
130896    29244       8.0
131196    29248       9.0
131295    29249      10.0
131406    29251      11.0
131572    29253      12.0
131590    29254      13.0
131782    29255      14.0
131788    29256      15.0
131970    29257      16.0
132090    35821      17.0
132137    35850      18.0
132211    35860      19.0
130574    12770      20.0
130405    12600      21.0
130470    12630      22.0
129867    12010      23.0
132380    43724      24.0
132442    43728      25.0
129915    12481      26.0
130240    12487      27.0
129991    12484      28.0
130125    12486      29.0
129443     8402      30.0

In [17]:
testing2 = dat2.loc[dat2['Trip_ID'] == 40569560]
tes2 = testing2[['STOP_ID', 'STOP_SEQ']]
tes2 = tes2.sort_values(by=['STOP_SEQ'])
tes2

        STOP_ID  STOP_SEQ
129524    10912       1.0
129635    10914       2.0
129763    10917       3.0
130781    29240       4.0
131058    29247       5.0
130620    25243       6.0
130962    29245       7.0
130888    29244       8.0
131245    29248       9.0
131300    29249      10.0
131411    29251      11.0
131527    29253      12.0
131634    29254      13.0
131769    29255      14.0
131826    29256      15.0
131893    29257      16.0
132095    35821      17.0
132173    35850      18.0
132221    35860      19.0
130575    12770      20.0
130333    12600      21.0
130412    12630      22.0
129787    12010      23.0
132348    43724      24.0
132437    43728      25.0
129957    12481      26.0
130210    12487      27.0
129989    12484      28.0
130177    12486      29.0
129374     8402      30.0

In [18]:
bus_mass = {
11: 11000,
26: 19051,
32: 11793,
36: 11793,
37: 12247,
43: 14913,
45: 19051,   
46: 18835,
60: 19051,
62: 19051,
68: 19051,
70: 12927,
72: 12927,
73: 12927,
80: 19051,
81: 19051,
82: 19051,
90: 12927,
91: 12927,
92: 12927,
95: 19051,
96: 19051
    }

In [19]:
trip183 = trip183.replace({'BusType': bus_mass})

In [22]:
trip_mass = trip183[['BusType', 'KeyTrip']]
trip_mass.head()

   BusType   KeyTrip
0    14913  40983895
1    14913  40983896
2    14913  40983897
3    14913  40983898
4    14913  40983904

In [25]:
trip_dict = dict(zip(trip_mass.KeyTrip, trip_mass.BusType))

In [ ]:
def bus_mass(period, direction, route):
    
    
    
    return

In [108]:
def route_ridership(period, direction, route):
    df = trip183unsum
    df = df.drop(df[(df.Period != period)].index)
    df = df.drop(df[(df.InOut != direction)].index)
    df = df.drop(df[(df.Route != route)].index)
    
    final_df = df.sort_values(by=['Trip_ID', 'STOP_SEQ'])
    riders = final_df.pivot(index='STOP_SEQ', columns='Trip_ID', values='AveLd')
    
    keyfind = list(riders.columns)
    mass_bus = [trip_dict[x] for x in keyfind]
    mode = mode_mass = max(set(mass_bus), key=mass_bus.count)
    rider_columns = list(riders.columns)
    kept_columns = []
    
    for i in range(0, len(mass_bus)):
        if mass_bus[i] == mode:
            kept_columns.append(rider_columns[i])
        
    riders_interm = riders[kept_columns]
    riders_kept = pd.DataFrame((riders_interm.mean(axis=1)), columns=['Mean'])
    riders_kept.Mean*=80
    
    return final_df, riders_kept, mode_mass

In [ ]:
mass_bus_75
rider_columns = list(riders_75.columns)
mode = max(set(mass_bus_75), key=mass_bus_75.count)

kept_columns = []
for i in range(0, len(mass_bus_75)):
    if mass_bus_75[i] == mode:
        kept_columns.append(rider_columns[i])

In [54]:
df_75, riders_75 = route_ridership('AM', 'I', 75)

In [55]:
riders_75.head()

Trip_ID,39682807,39683871,39683876,39683880,39683884,39683895,39683912,39683926,39683940,39683954,39683987,39683993,39684001,39684037,39684050,39684063,39684107,39684960
STOP_SEQ,,,,,,,,,,,,,,,,,,
1.0,2.2,1.9,2.4,6.3,5.9,5.6,3.0,4.0,2.8,3.8,5.0,3.7,1.8,4.1,4.5,3.8,6.7,3.4
2.0,3.2,2.2,2.6,9.5,6.7,6.4,3.5,5.0,2.8,4.4,6.4,5.0,2.0,4.7,6.3,4.2,10.5,4.6
3.0,3.2,2.2,2.7,9.8,7.1,6.6,3.5,5.1,3.2,4.5,6.6,5.0,1.8,4.8,6.4,4.1,10.8,4.7
4.0,4.7,2.9,5.2,15.3,9.1,7.8,4.4,6.4,4.6,7.3,8.4,6.7,2.4,6.0,7.6,5.6,13.0,5.3
5.0,4.9,3.2,5.8,19.9,11.3,9.8,5.2,7.3,4.8,10.6,10.1,7.3,4.0,7.1,8.1,6.2,15.4,6.5

In [110]:
df2_75, riders2_75, mass_75 = route_ridership('AM', 'I', 75)
mass_75

11793

In [72]:
#bus_mass_372 = trip_mass()
keyfind = list(riders_75.columns)
mass_bus_75 = [trip_dict[x] for x in keyfind]
#max(set(mass_bus_75), key=mass_bus_75.count)
mass_bus_75

[19051,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 11793,
 19051,
 19051,
 11793]

In [111]:
mass_bus_75
rider_columns = list(riders_75.columns)
mode = max(set(mass_bus_75), key=mass_bus_75.count)

kept_columns = []
for i in range(0, len(mass_bus_75)):
    if mass_bus_75[i] == mode:
        kept_columns.append(rider_columns[i])

In [83]:
riders_75[kept_columns]

Trip_ID,39683871,39683876,39683880,39683884,39683895,39683912,39683926,39683940,39683954,39683987,39683993,39684001,39684037,39684050,39684960
STOP_SEQ,,,,,,,,,,,,,,,
1.0,1.9,2.4,6.3,5.9,5.6,3.0,4.0,2.8,3.8,5.0,3.7,1.8,4.1,4.5,3.4
2.0,2.2,2.6,9.5,6.7,6.4,3.5,5.0,2.8,4.4,6.4,5.0,2.0,4.7,6.3,4.6
3.0,2.2,2.7,9.8,7.1,6.6,3.5,5.1,3.2,4.5,6.6,5.0,1.8,4.8,6.4,4.7
4.0,2.9,5.2,15.3,9.1,7.8,4.4,6.4,4.6,7.3,8.4,6.7,2.4,6.0,7.6,5.3
5.0,3.2,5.8,19.9,11.3,9.8,5.2,7.3,4.8,10.6,10.1,7.3,4.0,7.1,8.1,6.5
6.0,3.3,6.2,21.1,11.5,10.4,6.0,NaN,4.9,10.9,10.3,8.1,4.4,7.2,8.5,6.8
7.0,4.1,6.3,21.3,12.3,10.7,6.0,NaN,4.9,11.4,10.8,9.2,4.6,7.3,8.9,6.9
8.0,4.2,6.3,21.3,12.4,10.6,6.0,NaN,5.0,11.8,10.9,9.6,4.5,7.5,9.1,6.9
9.0,4.5,6.3,8.2,8.5,8.3,6.1,NaN,5.3,6.8,8.2,8.8,4.4,6.6,6.6,4.5
10.0,4.4,7.1,8.4,8.1,8.2,5.8,NaN,4.4,6.9,7.0,9.2,4.5,6.7,6.6,4.3
11.0,4.9,7.1,10.9,10.1,11.2,9.1,NaN,7.8,8.0,9.4,11.3,6.4,8.6,11.9,4.4
12.0,4.9,7.1,11.1,10.5,11.4,9.3,NaN,7.9,8.4,9.5,11.5,6.5,8.7,12.4,4.5
13.0,4.9,7.1,12.1,11.7,12.6,9.9,NaN,8.0,9.6,10.4,12.0,7.1,9.6,13.9,4.5
14.0,6.2,7.1,12.7,12.1,11.9,9.9,NaN,8.1,10.3,10.8,12.2,7.5,10.1,14.0,4.8
15.0,7.1,8.6,13.6,13.7,14.1,10.6,NaN,9.4,10.9,11.9,14.0,8.1,11.0,16.1,5.0
16.0,7.1,8.6,14.3,14.4,14.9,10.9,NaN,10.1,12.3,12.4,14.5,8.5,11.3,16.4,5.4
17.0,7.6,9.4,15.3,15.2,15.9,11.2,NaN,10.5,13.3,14.0,14.7,8.8,11.8,17.5,5.6
18.0,7.7,9.8,16.4,16.3,18.3,11.5,NaN,10.8,15.2,15.2,15.3,9.3,12.5,19.3,6.3
19.0,7.7,9.9,17.3,17.8,19.6,12.5,NaN,11.0,16.1,15.8,17.2,12.1,13.3,20.3,6.5
20.0,7.8,10.7,18.4,18.5,20.2,12.6,NaN,11.2,16.2,16.2,17.3,12.3,13.5,21.5,7.0
21.0,8.5,10.9,20.8,20.3,21.4,13.9,NaN,11.6,17.5,17.6,17.6,13.7,15.0,23.1,8.4
22.0,8.6,11.0,21.2,20.9,21.8,13.9,NaN,11.6,18.2,18.4,17.9,14.3,15.6,23.7,8.6
23.0,8.6,11.3,21.3,21.1,21.8,13.9,NaN,12.3,18.2,18.6,17.9,14.8,15.9,23.8,8.9
24.0,8.6,11.3,21.7,21.4,22.3,14.1,NaN,12.3,18.4,18.8,18.1,15.1,16.8,24.7,8.8
25.0,8.8,11.3,21.9,22.0,23.4,14.3,NaN,12.4,18.6,19.1,18.4,15.7,17.4,26.4,8.8
26.0,9.2,12.4,20.9,22.0,24.1,14.4,NaN,13.1,17.3,18.8,19.9,16.3,17.8,26.0,8.6
27.0,10.5,15.7,23.9,25.4,26.6,16.0,NaN,14.2,19.4,22.1,24.1,17.9,18.5,28.4,9.9
28.0,12.0,16.9,25.3,24.8,25.5,16.6,NaN,13.3,19.1,22.5,25.0,19.2,19.2,28.5,10.1
29.0,15.8,18.6,39.5,35.1,34.7,22.4,NaN,15.4,27.3,29.4,29.6,24.5,23.6,35.7,18.2
30.0,17.2,18.6,42.0,36.7,36.2,23.4,NaN,15.6,28.4,31.2,30.1,25.2,24.8,37.5,19.8
31.0,17.6,18.6,42.4,37.3,36.7,25.2,NaN,16.8,29.1,32.0,30.3,27.0,26.1,38.4,20.0
32.0,18.6,18.6,43.0,37.9,37.2,25.5,NaN,17.1,29.3,32.5,30.8,27.3,26.5,39.1,20.1
33.0,18.9,19.0,44.3,39.2,38.6,26.8,NaN,19.6,29.9,33.5,31.8,28.1,27.8,39.8,20.9
34.0,20.1,19.9,45.7,40.5,40.2,28.8,NaN,19.7,31.1,34.6,33.1,30.3,29.0,40.9,22.2
35.0,15.0,14.0,41.9,36.7,34.6,23.3,NaN,12.6,27.0,30.2,24.1,25.7,25.4,35.2,20.5
36.0,14.7,12.4,41.3,38.3,33.2,23.2,NaN,12.1,26.6,29.9,20.9,24.8,24.7,33.8,NaN
37.0,NaN,NaN,NaN,40.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38.0,NaN,NaN,NaN,41.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39.0,NaN,NaN,NaN,42.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40.0,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41.0,NaN,NaN,NaN,26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42.0,NaN,NaN,NaN,12.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43.0,NaN,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_test, rides_test, mass_test = route_ridership('')